theme = "onedarkerest"

[editor]
color-modes = true
cursorline = true
default-yank-register = "+"
gutters = ["diagnostics", "spacer", "diff"]
rulers = [101]
true-color = true
whitespace.render.nbsp = "all"
whitespace.render.space = "all"
whitespace.render.tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "separator", "file-type", "file-line-ending", "file-encoding"]
right = ["diagnostics", "selections", "primary-selection-length", "separator", "position-percentage", "total-line-numbers", "position"]

[editor.lsp]
# enable = false
display-messages = true
display-progress-messages = true

[keys.normal]
c = "change_selection_noyank"
A-c = "change_selection"
d = "delete_selection_noyank"
A-d = "delete_selection"
J = "join_selections_space"
A-J = "join_selections"
x = "extend_line"
Z = {Q = ":quit!", Z = ":write-quit!"}
