theme = "onedarkerest"

[editor]
color-modes = true
cursorline = true
default-yank-register = "+"
gutters = ["diagnostics", "spacer", "diff"]
rulers = [101]
text-width = 100
true-color = true
whitespace.render.nbsp = "all"
whitespace.render.space = "all"
whitespace.render.tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
# wrap-at-text-width = true
enable = false # https://github.com/helix-editor/helix/issues/12512

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "separator", "file-type", "file-line-ending", "file-encoding"]
right = ["register", "diagnostics", "separator", "spacer", "version-control", "spacer", "separator", "selections", "primary-selection-length", "separator", "spacer", "position-percentage", "total-line-numbers", "position"]

[editor.lsp]
# enable = false
display-messages = true
display-progress-messages = true

[keys.normal]
c = "change_selection_noyank"
A-c = "change_selection"
d = "delete_selection_noyank"
A-d = "delete_selection"
D = "delete_char_backward"
C-h = "jump_view_left"
H = "@vghv" # Extend to begining of line.
J = "join_selections_space"
A-J = "join_selections"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
L = "@vglv" # Extend to end of line.
A-r = ":config-reload"
C-r = ":reload-all"
X = "extend_line_above"
A-z = ":toggle soft-wrap.enable"
Z = {Q = ":quit-all!", Z = ":write-quit-all!"}
F8 = "@ '<down><ret>" # Go to next item in last picker.
S-F8 = "@ '<up><ret>" # Go to prev item in last picker.
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.select]
X = "extend_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
