return {
    {
        "LazyVim/LazyVim",
        opts = {
            colorscheme = "onedark",
            news = {
                neovim = true,
            },
        },
        keys = {
            { "<leader>L", enabled = false },
            { "<leader>l", enabled = false },
            { "<leader>lc", function() LazyVim.news.changelog() end, desc = "LazyVim Changelog", },
            { "<leader>le", "<Cmd>LazyExtras<CR>", desc = "Lazy Extras" },
            { "<leader>lh", function() Snacks.dashboard() end, desc = "Home screen", },
            { "<leader>ll", "<Cmd>Lazy<CR>", desc = "Lazy" },
        },
    },
    { "MagicDuck/grug-far.nvim", enabled = false },
    -- { "MunifTanjim/nui.nvim", enabled = false },
    { "akinsho/bufferline.nvim", enabled = false },
    { "catppuccin/nvim", enabled = false },
    { "folke/flash.nvim", enabled = false },
    -- { "folke/lazydev.nvim", enabled = false },
    -- { "folke/noice.nvim", enabled = false },
    -- { "folke/persistence.nvim", enabled = false },
    { "folke/todo-comments.nvim", enabled = false },
    { "folke/tokyonight.nvim", enabled = false },
    { "folke/trouble.nvim", enabled = false },
    { "folke/ts-comments.nvim", enabled = false },
    -- { "folke/which-key.nvim", enabled = false },
    { "lewis6991/gitsigns.nvim", enabled = false },
    { "mason-org/mason.nvim", enabled = false },
    { "mfussenegger/nvim-lint", enabled = false },
    { "neovim/nvim-lspconfig", enabled = false },
    { "nvim-lua/plenary.nvim", enabled = false },
    -- { "nvim-lualine/lualine.nvim", enabled = false },
    { "nvim-mini/mini.ai", enabled = false },
    -- { "nvim-mini/mini.icons", enabled = false },
    { "nvim-mini/mini.pairs", enabled = false },
    { "nvim-treesitter/nvim-treesitter", enabled = false },
    { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
    { "saghen/blink.cmp", enabled = false },
    { "stevearc/conform.nvim", enabled = false },
    { "windwp/nvim-ts-autotag", enabled = false },
}
