# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Aliases.
alias la='ls -lAFh --color=auto --group-directories-first'
alias ll='ls -lFh --color=auto --group-directories-first'

# Bash settings.
shopt -s extglob    # Enable extended glob patterns.
shopt -s globstar   # Enable ** glob pattern.
shopt -s histappend # Enable appending to $HISTFILE.
stty -ixon          # Disable scroll-lock (Ctrl-s, Ctrl-q).
tabs -4             # Set tab-stops to 4 characters.
