includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"bash",
	"fish",
	"intel",
	"linux",
	"neovim",
	"neovim-qt",
	"ssh",
	"sshd",
	"systemd",
	"systemd-networkd",
]

[files]

[variables]

[variables.linux]
default-kernel = "arch-surface"
lts = true
surface = true

[variables.systemd-networkd]
wlan = true
