includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"alacritty",
	"bash",
	"bat",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"intel",
	"jellyfin",
	"kde",
	"keepassxc",
	"linux",
	"mullvad-vpn",
	"neovim",
	"neovide",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[files]
"kde/kwinoutputconfig-fhcc.json" = "$XDG_CONFIG_HOME/kwinoutputconfig.json"

[variables]

[variables.games]
poe = { pob = true, awakened = false }

[variables.kde]
scale = 1.5

[variables.kde.kwinrc.tiling]
"6d9fe4df-7b78-5008-b1ee-2d74432082d4" = { "layoutDirection" = "horizontal", "tiles" = [ { "width" = 0.25 }, { "width" = 0.5}, { "width" = 0.25 } ] }

[variables.linux]
default-kernel = "arch-surface"
lts = true
surface = true
tpmoverride = true

[variables.systemd-networkd]
wlan = true
