includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"bash",
	"fish",
	"helix",
	"htop",
	"intel",
	"linux",
	"neovim",
	"neovim-qt",
	"paru",
	"ssh",
	"sshd",
	"systemd",
]

[files]

[variables]

[variables.linux]
surface = true
