includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"alacritty",
	"bash",
	"bat",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"intel",
	"jellyfin",
	"kde",
	"keepassxc",
	"libreoffice",
	"linux",
	"marksman",
	"meld",
	"neovide",
	"neovim",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[variables]

[variables.games]
poe = { pob = true, awakened = false }

[variables.kde.monitors.0]
edidHash = "df261155887e60481f3c52a2f9831a79"
edidIdentifier = "SEC 13634 0 0 2013 0"
height = 1440
refreshRate = 59955
scale = 1.5
uuid = "62d35f07-112c-454b-a436-f0c1bd912705"
width = 2160

[variables.linux]
default-kernel = "arch-surface"
lts = true
surface = true
tpmoverride = true
