includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"bash",
	"bat",
	"fish",
	"git",
	"helix",
	"htop",
	"neovim",
	"paru",
	"ripgrep",
	"starship",
	"systemd",
	"tig",
	"tmux",
	"wsl",
]

[files]

[variables]

[variables.linux]
fstrim = false
