includes = ["dotter/windows.toml", "dotter/local-includes.toml"]
packages = [
	"bash",
	"bat",
	"chrome",
	"delta",
	"dotnet",
	"firefox",
	"fish",
	"git",
	"helix",
	"keepass",
	"neovide",
	"neovim",
	"onedrive",
	"ripgrep",
	"rust",
	"ssh",
	"starship",
	"tig",
	"tmux",
	"tortoisegit",
	"vsvim",
	"windows",
	"windowsterminal",
	"winget",
	"xsv",
]

# [files]
# "msys2/etc/nsswitch.conf" = "C:/Users/mjboutin/msys64/etc/nsswitch.conf"

[variables]

[variables.git.user]
signingKey = "#~/.ssh/id_rsa"

[variables.shell]
SOURCE_HOME = "/d/Code"
