includes = ["dotter/local-includes.toml"]
packages = [
	"bash",
	"fish",
	"msys2",
	"windows",
	"wsl-client",
]

[files]
"msys2/etc/nsswitch.conf" = "C:/Users/mjboutin/msys64/etc/nsswitch.conf"

[variables]

[variables.shell]
SOURCE_HOME = "/d/Code"
