includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"amd",
	"bash",
	"fish",
	"linux",
	"neovim",
	"neovim-qt",
	"ssh",
	"sshd",
	"systemd",
	"systemd-networkd",
]

[files]

[variables]
