includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"amd",
	"bash",
	"bat",
	"delta",
	"fish",
	"git",
	"helix",
	"htop",
	"linux",
	"neovim",
	"neovim-qt",
	"paru",
	"ripgrep",
	"rust",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[files]

[variables]
