includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"alacritty",
	"amd",
	"bash",
	"bat",
	"ckb-next",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"kde",
	"keepassxc",
	"linux",
	"marksman",
	"meld",
	"mullvad-vpn",
	"neovide",
	"neovim",
	"nvidia",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[variables]

[variables.kde]
taskManagerScreen = 1

[variables.kde.monitors.0]
uuid = ""
refreshRate = 144000
