includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"alacritty",
	"amd",
	"bash",
	"bat",
	"ckb-next",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"kde",
	"keepassxc",
	"libreoffice",
	"linux",
	"marksman",
	"meld",
	"mullvad-vpn",
	"neovide",
	"neovim",
	"nvidia",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[files]
"kde/kwinoutputconfig-jvzx.json" = "$XDG_CONFIG_HOME/kwinoutputconfig.json"

[variables]

[variables.games]
dolphin = false

[variables.kde]
taskManagerScreen = 1

[variables.kde.kwinrc.tiling]
"5e038539-1348-5f39-b48c-d4ccf7420d2c" = { "layoutDirection" = "horizontal", "tiles" = [ { "width" = 0.25 }, { "width" = 0.5}, { "width" = 0.25 } ] }
"eefebce9-52d3-5bff-8490-46b59c2db081" = { "layoutDirection" = "horizontal", "tiles" = [ { "width" = 0.25 }, { "width" = 0.5}, { "width" = 0.25 } ] }
