includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"amd",
	"alacritty",
	"bash",
	"bat",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"kde",
	"keepassxc",
	"linux",
	"neovim",
	"neovim-qt",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[files]
"kde/kwinoutputconfig-jvzx.json" = "$XDG_CONFIG_HOME/kwinoutputconfig.json"

[variables]

[variables.kde]
taskManagerScreen = 1

[variables.kde.kwinrc.tiling]
"3d20ebec-4175-5f2e-8cf6-7acdf4420451" = { "layoutDirection" = "horizontal", "tiles" = [ { "width" = 0.25 }, { "width" = 0.5}, { "width" = 0.25 } ] }
"8e16c2eb-0e77-545e-bdf3-890cc9c55574" = { "layoutDirection" = "horizontal", "tiles" = [ { "width" = 0.25 }, { "width" = 0.5}, { "width" = 0.25 } ] }
