includes = ["dotter/local-includes.toml"]
packages = [
	"aconfmgr",
	"alacritty",
	"amd",
	"bash",
	"bat",
	"chrome",
	"ckb-next",
	"delta",
	"firefox",
	"fish",
	"games",
	"git",
	"helix",
	"htop",
	"kde",
	"keepassxc",
	"linux",
	"marksman",
	"meld",
	"neovide",
	"neovim",
	"nvidia",
	"onedrive",
	"paru",
	"ripgrep",
	"rust",
	"signal",
	"ssh",
	"sshd",
	"starship",
	"systemd",
	"systemd-networkd",
	"tig",
	"tmux",
	"xsv",
]

[variables]

[variables.games]
poe = { pob = true, awakened = true }

[variables.kde.monitors.0]
uuid = "54980d79-4769-4b90-9b63-3837327f0d5e"
scale = 1.75
refreshRate = 165000

[variables.linux]
asus = true
bluetooth = true
g14 = true
lts = true

[variables.systemd-networkd]
ethernet = false
wlan = true
