includes = ["dotter/windows.toml", "dotter/local-includes.toml"]
packages = [
	"bash",
	"fish",
	"msys2",
	"ssh",
	"windows",
	"wsl-client",
]

[files]

[variables]

[variables.shell]
SOURCE_HOME = "/d/Code"
