includes = ["dotter/windows.toml", "dotter/local-includes.toml"]
packages = [
	"bash",
	"bat",
	"chrome",
	"delta",
	"dotnet",
	"firefox",
	"fish",
	"git",
	"helix",
	"msys2",
	"neovim",
	"neovide",
	"neovim-qt",
	"onedrive",
	"pacman",
	"ripgrep",
	"rust",
	"ssh",
	"starship",
	"tig",
	"tmux",
	"tortoisegit",
	"vscode",
	"vsvim",
	"windows",
	"windowsterminal",
	"winget",
	"wsl-client",
	"xsv",
]

[files]

[variables]

[variables.shell]
SOURCE_HOME = "/d/Code"
