[git.variables.git.core]
autocrlf = "true"

[git.variables.git.credential]
helper = "" # Git credential manager is used implicitly.

[git.variables.git.http]
sslbackend = "schannel"

[git.variables.git.merge]
guitool = "tortoisemerge"

[helix.files]
"helix/config.toml" = "$APPDATA/helix/config.toml"
"helix/languages.toml" = "$APPDATA/helix/languages.toml"
"helix/themes/onedarkerest.toml" = "$APPDATA/helix/themes/onedarkerest.toml"

[shell.variables.ssh]
connection-sharing = false

[starship.variables.starship]
command_timeout = 10000

[tmux.variables.tmux]
default-terminal = "xterm-256color"
