[helix.files]
"helix/config.toml" = "$APPDATA/helix/config.toml"
"helix/languages.toml" = "$APPDATA/helix/languages.toml"

[shell.variables.ssh]
connection-sharing = false

[starship.variables.starship]
command_timeout = 10000

[tmux.variables.tmux]
default-terminal = "xterm-256color"
